/* ============================================
   PEAKPOINT SAT PREP - Resource Library data
   Auto-generated from 'PeakPoint Materials Inventory.csv'.
   104 resources.
   ============================================ */
window.PP_RESOURCES = [
  {
    "id": "math-46",
    "title": "Math Hard Questions Drill 1",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Mixed hard math",
    "description": "Drill Set — Mixed hard math",
    "notes": "",
    "filePath": "resources/math/Math Hard Questions Drill 1.pdf",
    "downloadUrl": "resources/math/Math Hard Questions Drill 1.pdf"
  },
  {
    "id": "math-36",
    "title": "Math Hard Questions Drill 10",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Mixed hard math",
    "description": "Drill Set — Mixed hard math",
    "notes": "",
    "filePath": "resources/math/Math Hard Questions Drill 10.pdf",
    "downloadUrl": "resources/math/Math Hard Questions Drill 10.pdf"
  },
  {
    "id": "math-37",
    "title": "Math Hard Questions Drill 11",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Mixed hard math",
    "description": "Drill Set — Mixed hard math",
    "notes": "",
    "filePath": "resources/math/Math Hard Questions Drill 11.pdf",
    "downloadUrl": "resources/math/Math Hard Questions Drill 11.pdf"
  },
  {
    "id": "math-38",
    "title": "Math Hard Questions Drill 12",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Mixed hard math",
    "description": "Drill Set — Mixed hard math",
    "notes": "",
    "filePath": "resources/math/Math Hard Questions Drill 12.pdf",
    "downloadUrl": "resources/math/Math Hard Questions Drill 12.pdf"
  },
  {
    "id": "math-45",
    "title": "Math Hard Questions Drill 2",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Mixed hard math",
    "description": "Drill Set — Mixed hard math",
    "notes": "",
    "filePath": "resources/math/Math Hard Questions Drill 2.pdf",
    "downloadUrl": "resources/math/Math Hard Questions Drill 2.pdf"
  },
  {
    "id": "math-44",
    "title": "Math Hard Questions Drill 3",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Mixed hard math",
    "description": "Drill Set — Mixed hard math",
    "notes": "",
    "filePath": "resources/math/Math Hard Questions Drill 3.pdf",
    "downloadUrl": "resources/math/Math Hard Questions Drill 3.pdf"
  },
  {
    "id": "math-43",
    "title": "Math Hard Questions Drill 4",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Mixed hard math (incl. radicals, radians)",
    "description": "Drill Set — Mixed hard math (incl. radicals, radians)",
    "notes": "",
    "filePath": "resources/math/Math Hard Questions Drill 4.pdf",
    "downloadUrl": "resources/math/Math Hard Questions Drill 4.pdf"
  },
  {
    "id": "math-42",
    "title": "Math Hard Questions Drill 5",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Mixed hard math (incl. box plots, circles)",
    "description": "Drill Set — Mixed hard math (incl. box plots, circles)",
    "notes": "",
    "filePath": "resources/math/Math Hard Questions Drill 5.pdf",
    "downloadUrl": "resources/math/Math Hard Questions Drill 5.pdf"
  },
  {
    "id": "math-41",
    "title": "Math Hard Questions Drill 6",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Mixed hard math (incl. scatterplots)",
    "description": "Drill Set — Mixed hard math (incl. scatterplots)",
    "notes": "",
    "filePath": "resources/math/Math Hard Questions Drill 6.pdf",
    "downloadUrl": "resources/math/Math Hard Questions Drill 6.pdf"
  },
  {
    "id": "math-40",
    "title": "Math Hard Questions Drill 7",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Mixed hard math (incl. volume, histograms)",
    "description": "Drill Set — Mixed hard math (incl. volume, histograms)",
    "notes": "",
    "filePath": "resources/math/Math Hard Questions Drill 7.pdf",
    "downloadUrl": "resources/math/Math Hard Questions Drill 7.pdf"
  },
  {
    "id": "math-39",
    "title": "Math Hard Questions Drill 8",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Mixed hard math",
    "description": "Drill Set — Mixed hard math",
    "notes": "",
    "filePath": "resources/math/Math Hard Questions Drill 8.pdf",
    "downloadUrl": "resources/math/Math Hard Questions Drill 8.pdf"
  },
  {
    "id": "math-35",
    "title": "Math Hard Questions Drill 9",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Mixed hard math",
    "description": "Drill Set — Mixed hard math",
    "notes": "",
    "filePath": "resources/math/Math Hard Questions Drill 9.pdf",
    "downloadUrl": "resources/math/Math Hard Questions Drill 9.pdf"
  },
  {
    "id": "math-50",
    "title": "Percent Problems Drill Sheet",
    "section": "Math",
    "materialType": "Drill Set",
    "topic": "Percent phrasing translations",
    "description": "Drill Set — Percent phrasing translations. 1-page drill",
    "notes": "1-page drill",
    "filePath": "resources/math/Percent Problems Drill Sheet.pdf",
    "downloadUrl": "resources/math/Percent Problems Drill Sheet.pdf"
  },
  {
    "id": "math-9",
    "title": "Math Hard Advanced Math Answer Explanations",
    "section": "Math",
    "materialType": "Explanation Guide",
    "topic": "Advanced Math (hard)",
    "description": "Explanation Guide — Advanced Math (hard). Teacher version with rationales",
    "notes": "Teacher version with rationales",
    "filePath": "resources/math/Math Hard Advanced Math Answer Explanations.pdf",
    "downloadUrl": "resources/math/Math Hard Advanced Math Answer Explanations.pdf"
  },
  {
    "id": "math-11",
    "title": "Math Hard Algebra Answer Explanations",
    "section": "Math",
    "materialType": "Explanation Guide",
    "topic": "Algebra (hard)",
    "description": "Explanation Guide — Algebra (hard). Teacher version with rationales",
    "notes": "Teacher version with rationales",
    "filePath": "resources/math/Math Hard Algebra Answer Explanations.pdf",
    "downloadUrl": "resources/math/Math Hard Algebra Answer Explanations.pdf"
  },
  {
    "id": "math-13",
    "title": "Math Hard Geometry Answer Explanations",
    "section": "Math",
    "materialType": "Explanation Guide",
    "topic": "Geometry and Trigonometry (hard)",
    "description": "Explanation Guide — Geometry and Trigonometry (hard). Teacher version with rationales",
    "notes": "Teacher version with rationales",
    "filePath": "resources/math/Math Hard Geometry Answer Explanations.pdf",
    "downloadUrl": "resources/math/Math Hard Geometry Answer Explanations.pdf"
  },
  {
    "id": "math-15",
    "title": "Math Hard Problem Solving Answer Explanations",
    "section": "Math",
    "materialType": "Explanation Guide",
    "topic": "Problem Solving and Data Analysis (hard)",
    "description": "Explanation Guide — Problem Solving and Data Analysis (hard). Teacher version with rationales",
    "notes": "Teacher version with rationales",
    "filePath": "resources/math/Math Hard Problem Solving Answer Explanations.pdf",
    "downloadUrl": "resources/math/Math Hard Problem Solving Answer Explanations.pdf"
  },
  {
    "id": "math-49",
    "title": "Quadratics Formulas and Practice Worksheet",
    "section": "Math",
    "materialType": "Formula Sheet",
    "topic": "Quadratics",
    "description": "Formula Sheet — Quadratics. Formula reference plus harder practice",
    "notes": "Formula reference plus harder practice",
    "filePath": "resources/math/Quadratics Formulas and Practice Worksheet.pdf",
    "downloadUrl": "resources/math/Quadratics Formulas and Practice Worksheet.pdf"
  },
  {
    "id": "math-63",
    "title": "SAT Math Reference Formula Sheet",
    "section": "Math",
    "materialType": "Formula Sheet",
    "topic": "Official SAT math reference",
    "description": "Formula Sheet — Official SAT math reference. Geometry formulas + module directions",
    "notes": "Geometry formulas + module directions",
    "filePath": "resources/math/SAT Math Reference Formula Sheet.pdf",
    "downloadUrl": "resources/math/SAT Math Reference Formula Sheet.pdf"
  },
  {
    "id": "math-53",
    "title": "Math Practice Test 2312Av1 Module 1",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 1",
    "description": "Mini Practice Test — Mixed math, Module 1. Used as course final, Module 1",
    "notes": "Used as course final, Module 1",
    "filePath": "resources/math/Math Practice Test 2312Av1 Module 1.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2312Av1 Module 1.pdf"
  },
  {
    "id": "math-52",
    "title": "Math Practice Test 2312Av1 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Used as course final, Module 2",
    "notes": "Used as course final, Module 2",
    "filePath": "resources/math/Math Practice Test 2312Av1 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2312Av1 Module 2.pdf"
  },
  {
    "id": "math-17",
    "title": "Math Practice Test 2403AvA Module 1",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 1",
    "description": "Mini Practice Test — Mixed math, Module 1. Used as diagnostic test (35 min)",
    "notes": "Used as diagnostic test (35 min)",
    "filePath": "resources/math/Math Practice Test 2403AvA Module 1.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2403AvA Module 1.pdf"
  },
  {
    "id": "math-16",
    "title": "Math Practice Test 2403AvA Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Used as diagnostic test (35 min)",
    "notes": "Used as diagnostic test (35 min)",
    "filePath": "resources/math/Math Practice Test 2403AvA Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2403AvA Module 2.pdf"
  },
  {
    "id": "math-59",
    "title": "Math Practice Test 2403AvB Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. In-class 7/23",
    "notes": "In-class 7/23",
    "filePath": "resources/math/Math Practice Test 2403AvB Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2403AvB Module 2.pdf"
  },
  {
    "id": "math-25",
    "title": "Math Practice Test 2406Av1 Module 1",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 1",
    "description": "Mini Practice Test — Mixed math, Module 1. Self-study",
    "notes": "Self-study",
    "filePath": "resources/math/Math Practice Test 2406Av1 Module 1.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2406Av1 Module 1.pdf"
  },
  {
    "id": "math-26",
    "title": "Math Practice Test 2406Av1 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Self-study",
    "notes": "Self-study",
    "filePath": "resources/math/Math Practice Test 2406Av1 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2406Av1 Module 2.pdf"
  },
  {
    "id": "math-27",
    "title": "Math Practice Test 2406Av2 Module 1",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 1",
    "description": "Mini Practice Test — Mixed math, Module 1. Self-study; scanned screenshots",
    "notes": "Self-study; scanned screenshots",
    "filePath": "resources/math/Math Practice Test 2406Av2 Module 1.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2406Av2 Module 1.pdf"
  },
  {
    "id": "math-28",
    "title": "Math Practice Test 2406Av2 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Self-study",
    "notes": "Self-study",
    "filePath": "resources/math/Math Practice Test 2406Av2 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2406Av2 Module 2.pdf"
  },
  {
    "id": "math-29",
    "title": "Math Practice Test 2406Av4 Module 1",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 1",
    "description": "Mini Practice Test — Mixed math, Module 1. Self-study",
    "notes": "Self-study",
    "filePath": "resources/math/Math Practice Test 2406Av4 Module 1.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2406Av4 Module 1.pdf"
  },
  {
    "id": "math-30",
    "title": "Math Practice Test 2406Av4 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Self-study",
    "notes": "Self-study",
    "filePath": "resources/math/Math Practice Test 2406Av4 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2406Av4 Module 2.pdf"
  },
  {
    "id": "math-31",
    "title": "Math Practice Test 2406Av5 Module 1",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 1",
    "description": "Mini Practice Test — Mixed math, Module 1. Self-study",
    "notes": "Self-study",
    "filePath": "resources/math/Math Practice Test 2406Av5 Module 1.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2406Av5 Module 1.pdf"
  },
  {
    "id": "math-32",
    "title": "Math Practice Test 2406Av5 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Self-study",
    "notes": "Self-study",
    "filePath": "resources/math/Math Practice Test 2406Av5 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2406Av5 Module 2.pdf"
  },
  {
    "id": "math-33",
    "title": "Math Practice Test 2406U Module 1",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 1",
    "description": "Mini Practice Test — Mixed math, Module 1. Self-study",
    "notes": "Self-study",
    "filePath": "resources/math/Math Practice Test 2406U Module 1.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2406U Module 1.pdf"
  },
  {
    "id": "math-34",
    "title": "Math Practice Test 2406U Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Self-study",
    "notes": "Self-study",
    "filePath": "resources/math/Math Practice Test 2406U Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2406U Module 2.pdf"
  },
  {
    "id": "math-58",
    "title": "Math Practice Test 2408Av2 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. In-class 7/24",
    "notes": "In-class 7/24",
    "filePath": "resources/math/Math Practice Test 2408Av2 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2408Av2 Module 2.pdf"
  },
  {
    "id": "math-24",
    "title": "Math Practice Test 2410Av1 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Homework due 7/17",
    "notes": "Homework due 7/17",
    "filePath": "resources/math/Math Practice Test 2410Av1 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2410Av1 Module 2.pdf"
  },
  {
    "id": "math-21",
    "title": "Math Practice Test 2410Av2 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Homework due 7/28",
    "notes": "Homework due 7/28",
    "filePath": "resources/math/Math Practice Test 2410Av2 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2410Av2 Module 2.pdf"
  },
  {
    "id": "math-23",
    "title": "Math Practice Test 2410Uv1 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Homework due 7/21",
    "notes": "Homework due 7/21",
    "filePath": "resources/math/Math Practice Test 2410Uv1 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2410Uv1 Module 2.pdf"
  },
  {
    "id": "math-60",
    "title": "Math Practice Test 2411Av1 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. In-class 7/22",
    "notes": "In-class 7/22",
    "filePath": "resources/math/Math Practice Test 2411Av1 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2411Av1 Module 2.pdf"
  },
  {
    "id": "math-20",
    "title": "Math Practice Test 2411Av2 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Homework due 7/29",
    "notes": "Homework due 7/29",
    "filePath": "resources/math/Math Practice Test 2411Av2 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2411Av2 Module 2.pdf"
  },
  {
    "id": "math-22",
    "title": "Math Practice Test 2412Av2 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Homework due 7/23",
    "notes": "Homework due 7/23",
    "filePath": "resources/math/Math Practice Test 2412Av2 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2412Av2 Module 2.pdf"
  },
  {
    "id": "math-55",
    "title": "Math Practice Test 2412Uv2 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. In-class 7/29",
    "notes": "In-class 7/29",
    "filePath": "resources/math/Math Practice Test 2412Uv2 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2412Uv2 Module 2.pdf"
  },
  {
    "id": "math-54",
    "title": "Math Practice Test 2503Av1 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. In-class 7/30",
    "notes": "In-class 7/30",
    "filePath": "resources/math/Math Practice Test 2503Av1 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2503Av1 Module 2.pdf"
  },
  {
    "id": "math-61",
    "title": "Math Practice Test 2503U2 Module 1",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 1",
    "description": "Mini Practice Test — Mixed math, Module 1. Mock test 7/18",
    "notes": "Mock test 7/18",
    "filePath": "resources/math/Math Practice Test 2503U2 Module 1.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2503U2 Module 1.pdf"
  },
  {
    "id": "math-62",
    "title": "Math Practice Test 2503U2 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Mock test 7/18",
    "notes": "Mock test 7/18",
    "filePath": "resources/math/Math Practice Test 2503U2 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2503U2 Module 2.pdf"
  },
  {
    "id": "math-57",
    "title": "Math Practice Test 2505Av2 Module 1",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 1",
    "description": "Mini Practice Test — Mixed math, Module 1. Mock test 7/25",
    "notes": "Mock test 7/25",
    "filePath": "resources/math/Math Practice Test 2505Av2 Module 1.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2505Av2 Module 1.pdf"
  },
  {
    "id": "math-56",
    "title": "Math Practice Test 2505Av2 Module 2",
    "section": "Math",
    "materialType": "Mini Practice Test",
    "topic": "Mixed math, Module 2",
    "description": "Mini Practice Test — Mixed math, Module 2. Mock test 7/25",
    "notes": "Mock test 7/25",
    "filePath": "resources/math/Math Practice Test 2505Av2 Module 2.pdf",
    "downloadUrl": "resources/math/Math Practice Test 2505Av2 Module 2.pdf"
  },
  {
    "id": "math-51",
    "title": "Area and Volume Scale Factor Worksheet",
    "section": "Math",
    "materialType": "Targeted Practice Questions",
    "topic": "Area/volume ratios, scale factor",
    "description": "Targeted Practice Questions — Area/volume ratios, scale factor",
    "notes": "",
    "filePath": "resources/math/Area and Volume Scale Factor Worksheet.pdf",
    "downloadUrl": "resources/math/Area and Volume Scale Factor Worksheet.pdf"
  },
  {
    "id": "math-8",
    "title": "Math Hard Advanced Math Practice Questions",
    "section": "Math",
    "materialType": "Targeted Practice Questions",
    "topic": "Advanced Math (hard)",
    "description": "Targeted Practice Questions — Advanced Math (hard). Externally released SAT-style practice (Aug 2025)",
    "notes": "Externally released SAT-style practice (Aug 2025)",
    "filePath": "resources/math/Math Hard Advanced Math Practice Questions.pdf",
    "downloadUrl": "resources/math/Math Hard Advanced Math Practice Questions.pdf"
  },
  {
    "id": "math-10",
    "title": "Math Hard Algebra Practice Questions",
    "section": "Math",
    "materialType": "Targeted Practice Questions",
    "topic": "Algebra (hard)",
    "description": "Targeted Practice Questions — Algebra (hard). Externally released SAT-style practice (Aug 2025)",
    "notes": "Externally released SAT-style practice (Aug 2025)",
    "filePath": "resources/math/Math Hard Algebra Practice Questions.pdf",
    "downloadUrl": "resources/math/Math Hard Algebra Practice Questions.pdf"
  },
  {
    "id": "math-12",
    "title": "Math Hard Geometry Practice Questions",
    "section": "Math",
    "materialType": "Targeted Practice Questions",
    "topic": "Geometry and Trigonometry (hard)",
    "description": "Targeted Practice Questions — Geometry and Trigonometry (hard). Externally released SAT-style practice (Aug 2025)",
    "notes": "Externally released SAT-style practice (Aug 2025)",
    "filePath": "resources/math/Math Hard Geometry Practice Questions.pdf",
    "downloadUrl": "resources/math/Math Hard Geometry Practice Questions.pdf"
  },
  {
    "id": "math-14",
    "title": "Math Hard Problem Solving Practice Questions",
    "section": "Math",
    "materialType": "Targeted Practice Questions",
    "topic": "Problem Solving and Data Analysis (hard)",
    "description": "Targeted Practice Questions — Problem Solving and Data Analysis (hard). Externally released SAT-style practice (Aug 2025)",
    "notes": "Externally released SAT-style practice (Aug 2025)",
    "filePath": "resources/math/Math Hard Problem Solving Practice Questions.pdf",
    "downloadUrl": "resources/math/Math Hard Problem Solving Practice Questions.pdf"
  },
  {
    "id": "math-48",
    "title": "Percents Worksheet 2",
    "section": "Math",
    "materialType": "Targeted Practice Questions",
    "topic": "Percents",
    "description": "Targeted Practice Questions — Percents",
    "notes": "",
    "filePath": "resources/math/Percents Worksheet 2.pdf",
    "downloadUrl": "resources/math/Percents Worksheet 2.pdf"
  },
  {
    "id": "math-47",
    "title": "Right Triangles and Similarity Worksheet",
    "section": "Math",
    "materialType": "Targeted Practice Questions",
    "topic": "Right triangles, similarity",
    "description": "Targeted Practice Questions — Right triangles, similarity",
    "notes": "",
    "filePath": "resources/math/Right Triangles and Similarity Worksheet.pdf",
    "downloadUrl": "resources/math/Right Triangles and Similarity Worksheet.pdf"
  },
  {
    "id": "reading-1",
    "title": "Reading Craft and Structure Answer Explanations",
    "section": "Reading",
    "materialType": "Explanation Guide",
    "topic": "Craft and Structure",
    "description": "Explanation Guide — Craft and Structure. Teacher version with rationales",
    "notes": "Teacher version with rationales",
    "filePath": "resources/reading/Reading Craft and Structure Answer Explanations.pdf",
    "downloadUrl": "resources/reading/Reading Craft and Structure Answer Explanations.pdf"
  },
  {
    "id": "reading-5",
    "title": "Reading Information and Ideas Answer Explanations",
    "section": "Reading",
    "materialType": "Explanation Guide",
    "topic": "Information and Ideas",
    "description": "Explanation Guide — Information and Ideas. Teacher version with rationales",
    "notes": "Teacher version with rationales",
    "filePath": "resources/reading/Reading Information and Ideas Answer Explanations.pdf",
    "downloadUrl": "resources/reading/Reading Information and Ideas Answer Explanations.pdf"
  },
  {
    "id": "reading-95",
    "title": "Text Structure and Purpose Notes",
    "section": "Reading",
    "materialType": "Lesson Notes",
    "topic": "Text structures (They Say I Say etc.)",
    "description": "Lesson Notes — Text structures (They Say I Say etc.)",
    "notes": "",
    "filePath": "resources/reading/Text Structure and Purpose Notes.pdf",
    "downloadUrl": "resources/reading/Text Structure and Purpose Notes.pdf"
  },
  {
    "id": "reading-85",
    "title": "Command of Evidence Practice Set 2",
    "section": "Reading",
    "materialType": "Targeted Practice Questions",
    "topic": "Command of Evidence",
    "description": "Targeted Practice Questions — Command of Evidence. External SAT-style practice; set H2 (Homework 14)",
    "notes": "External SAT-style practice; set H2 (Homework 14)",
    "filePath": "resources/reading/Command of Evidence Practice Set 2.pdf",
    "downloadUrl": "resources/reading/Command of Evidence Practice Set 2.pdf"
  },
  {
    "id": "reading-79",
    "title": "Command of Evidence Practice Set 3",
    "section": "Reading",
    "materialType": "Targeted Practice Questions",
    "topic": "Command of Evidence",
    "description": "Targeted Practice Questions — Command of Evidence. External SAT-style practice; set H3",
    "notes": "External SAT-style practice; set H3",
    "filePath": "resources/reading/Command of Evidence Practice Set 3.pdf",
    "downloadUrl": "resources/reading/Command of Evidence Practice Set 3.pdf"
  },
  {
    "id": "reading-77",
    "title": "Command of Evidence Practice Set 4",
    "section": "Reading",
    "materialType": "Targeted Practice Questions",
    "topic": "Command of Evidence",
    "description": "Targeted Practice Questions — Command of Evidence. External SAT-style practice; set H4",
    "notes": "External SAT-style practice; set H4",
    "filePath": "resources/reading/Command of Evidence Practice Set 4.pdf",
    "downloadUrl": "resources/reading/Command of Evidence Practice Set 4.pdf"
  },
  {
    "id": "reading-81",
    "title": "Command of Evidence Practice Set 5",
    "section": "Reading",
    "materialType": "Targeted Practice Questions",
    "topic": "Command of Evidence",
    "description": "Targeted Practice Questions — Command of Evidence. External SAT-style practice; set H5 (Homework 17)",
    "notes": "External SAT-style practice; set H5 (Homework 17)",
    "filePath": "resources/reading/Command of Evidence Practice Set 5.pdf",
    "downloadUrl": "resources/reading/Command of Evidence Practice Set 5.pdf"
  },
  {
    "id": "reading-90",
    "title": "Inferences Practice Set 1",
    "section": "Reading",
    "materialType": "Targeted Practice Questions",
    "topic": "Inferences",
    "description": "Targeted Practice Questions — Inferences. External SAT-style practice; set H1 (Homework 11)",
    "notes": "External SAT-style practice; set H1 (Homework 11)",
    "filePath": "resources/reading/Inferences Practice Set 1.pdf",
    "downloadUrl": "resources/reading/Inferences Practice Set 1.pdf"
  },
  {
    "id": "reading-0",
    "title": "Reading Craft and Structure Practice Questions",
    "section": "Reading",
    "materialType": "Targeted Practice Questions",
    "topic": "Craft and Structure",
    "description": "Targeted Practice Questions — Craft and Structure. Externally released SAT-style practice (Aug 2025)",
    "notes": "Externally released SAT-style practice (Aug 2025)",
    "filePath": "resources/reading/Reading Craft and Structure Practice Questions.pdf",
    "downloadUrl": "resources/reading/Reading Craft and Structure Practice Questions.pdf"
  },
  {
    "id": "reading-4",
    "title": "Reading Information and Ideas Practice Questions",
    "section": "Reading",
    "materialType": "Targeted Practice Questions",
    "topic": "Information and Ideas",
    "description": "Targeted Practice Questions — Information and Ideas. Externally released SAT-style practice (Aug 2025)",
    "notes": "Externally released SAT-style practice (Aug 2025)",
    "filePath": "resources/reading/Reading Information and Ideas Practice Questions.pdf",
    "downloadUrl": "resources/reading/Reading Information and Ideas Practice Questions.pdf"
  },
  {
    "id": "reading-91",
    "title": "Text Structure and Purpose Practice Set 2",
    "section": "Reading",
    "materialType": "Targeted Practice Questions",
    "topic": "Text Structure and Purpose",
    "description": "Targeted Practice Questions — Text Structure and Purpose. External SAT-style practice; set H2 (Homework 10)",
    "notes": "External SAT-style practice; set H2 (Homework 10)",
    "filePath": "resources/reading/Text Structure and Purpose Practice Set 2.pdf",
    "downloadUrl": "resources/reading/Text Structure and Purpose Practice Set 2.pdf"
  },
  {
    "id": "writing-69",
    "title": "Writing Practice Sets Answer Key",
    "section": "Writing",
    "materialType": "Answer Key",
    "topic": "Transitions and writing",
    "description": "Answer Key — Transitions and writing. Answers/explanations for Practice Sets 1-5",
    "notes": "Answers/explanations for Practice Sets 1-5",
    "filePath": "resources/writing/Writing Practice Sets Answer Key.pdf",
    "downloadUrl": "resources/writing/Writing Practice Sets Answer Key.pdf"
  },
  {
    "id": "writing-98",
    "title": "Boundaries Rule 1 Cheat Sheet",
    "section": "Writing",
    "materialType": "Cheat Sheet",
    "topic": "Boundaries - combining independent clauses",
    "description": "Cheat Sheet — Boundaries - combining independent clauses",
    "notes": "",
    "filePath": "resources/writing/Boundaries Rule 1 Cheat Sheet.pdf",
    "downloadUrl": "resources/writing/Boundaries Rule 1 Cheat Sheet.pdf"
  },
  {
    "id": "writing-99",
    "title": "Boundaries Rule 2 Cheat Sheet",
    "section": "Writing",
    "materialType": "Cheat Sheet",
    "topic": "Boundaries - punctuation within clauses",
    "description": "Cheat Sheet — Boundaries - punctuation within clauses",
    "notes": "",
    "filePath": "resources/writing/Boundaries Rule 2 Cheat Sheet.pdf",
    "downloadUrl": "resources/writing/Boundaries Rule 2 Cheat Sheet.pdf"
  },
  {
    "id": "writing-100",
    "title": "Boundaries Rule 3 Cheat Sheet",
    "section": "Writing",
    "materialType": "Cheat Sheet",
    "topic": "Boundaries - essential vs nonessential",
    "description": "Cheat Sheet — Boundaries - essential vs nonessential",
    "notes": "",
    "filePath": "resources/writing/Boundaries Rule 3 Cheat Sheet.pdf",
    "downloadUrl": "resources/writing/Boundaries Rule 3 Cheat Sheet.pdf"
  },
  {
    "id": "writing-3",
    "title": "Writing Expression of Ideas Answer Explanations",
    "section": "Writing",
    "materialType": "Explanation Guide",
    "topic": "Expression of Ideas",
    "description": "Explanation Guide — Expression of Ideas. Teacher version with rationales",
    "notes": "Teacher version with rationales",
    "filePath": "resources/writing/Writing Expression of Ideas Answer Explanations.pdf",
    "downloadUrl": "resources/writing/Writing Expression of Ideas Answer Explanations.pdf"
  },
  {
    "id": "writing-7",
    "title": "Writing Standard English Conventions Answer Explanations",
    "section": "Writing",
    "materialType": "Explanation Guide",
    "topic": "Standard English Conventions",
    "description": "Explanation Guide — Standard English Conventions. Teacher version with rationales",
    "notes": "Teacher version with rationales",
    "filePath": "resources/writing/Writing Standard English Conventions Answer Explanations.pdf",
    "downloadUrl": "resources/writing/Writing Standard English Conventions Answer Explanations.pdf"
  },
  {
    "id": "writing-102",
    "title": "Complex Lists Punctuation Guide",
    "section": "Writing",
    "materialType": "Grammar Rules",
    "topic": "Complex lists (semicolon lists)",
    "description": "Grammar Rules — Complex lists (semicolon lists)",
    "notes": "",
    "filePath": "resources/writing/Complex Lists Punctuation Guide.pdf",
    "downloadUrl": "resources/writing/Complex Lists Punctuation Guide.pdf"
  },
  {
    "id": "writing-97",
    "title": "Functional Equivalence Punctuation Rule",
    "section": "Writing",
    "materialType": "Grammar Rules",
    "topic": "Functional equivalence; periods vs semicolons",
    "description": "Grammar Rules — Functional equivalence; periods vs semicolons",
    "notes": "",
    "filePath": "resources/writing/Functional Equivalence Punctuation Rule.pdf",
    "downloadUrl": "resources/writing/Functional Equivalence Punctuation Rule.pdf"
  },
  {
    "id": "writing-94",
    "title": "Possessives Grammar Rules",
    "section": "Writing",
    "materialType": "Grammar Rules",
    "topic": "Possessives",
    "description": "Grammar Rules — Possessives. 1-page rules sheet",
    "notes": "1-page rules sheet",
    "filePath": "resources/writing/Possessives Grammar Rules.pdf",
    "downloadUrl": "resources/writing/Possessives Grammar Rules.pdf"
  },
  {
    "id": "writing-101",
    "title": "Punctuation Boundaries Masterlist",
    "section": "Writing",
    "materialType": "Grammar Rules",
    "topic": "Boundaries - complete reference",
    "description": "Grammar Rules — Boundaries - complete reference",
    "notes": "",
    "filePath": "resources/writing/Punctuation Boundaries Masterlist.pdf",
    "downloadUrl": "resources/writing/Punctuation Boundaries Masterlist.pdf"
  },
  {
    "id": "writing-96",
    "title": "Verb Tenses Grammar Rules",
    "section": "Writing",
    "materialType": "Grammar Rules",
    "topic": "Verb tenses",
    "description": "Grammar Rules — Verb tenses",
    "notes": "",
    "filePath": "resources/writing/Verb Tenses Grammar Rules.pdf",
    "downloadUrl": "resources/writing/Verb Tenses Grammar Rules.pdf"
  },
  {
    "id": "writing-103",
    "title": "Transitions Rules Strategy Guide",
    "section": "Writing",
    "materialType": "Strategy Guide",
    "topic": "Transition questions",
    "description": "Strategy Guide — Transition questions",
    "notes": "",
    "filePath": "resources/writing/Transitions Rules Strategy Guide.pdf",
    "downloadUrl": "resources/writing/Transitions Rules Strategy Guide.pdf"
  },
  {
    "id": "writing-93",
    "title": "Writing Questions Quick Guide",
    "section": "Writing",
    "materialType": "Strategy Guide",
    "topic": "Approach to writing questions",
    "description": "Strategy Guide — Approach to writing questions",
    "notes": "",
    "filePath": "resources/writing/Writing Questions Quick Guide.pdf",
    "downloadUrl": "resources/writing/Writing Questions Quick Guide.pdf"
  },
  {
    "id": "writing-80",
    "title": "Boundaries Rule 1 Practice Questions",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Boundaries - Rule 1",
    "description": "Targeted Practice Questions — Boundaries - Rule 1. External SAT-style practice; 36 pages",
    "notes": "External SAT-style practice; 36 pages",
    "filePath": "resources/writing/Boundaries Rule 1 Practice Questions.pdf",
    "downloadUrl": "resources/writing/Boundaries Rule 1 Practice Questions.pdf"
  },
  {
    "id": "writing-78",
    "title": "Form Structure and Sense Practice Set",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Form, Structure, and Sense",
    "description": "Targeted Practice Questions — Form, Structure, and Sense. Scanned from DSAT R&W practice book",
    "notes": "Scanned from DSAT R&W practice book",
    "filePath": "resources/writing/Form Structure and Sense Practice Set.pdf",
    "downloadUrl": "resources/writing/Form Structure and Sense Practice Set.pdf"
  },
  {
    "id": "writing-72",
    "title": "Modifiers Practice Questions",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Modifiers",
    "description": "Targeted Practice Questions — Modifiers. External SAT-style practice",
    "notes": "External SAT-style practice",
    "filePath": "resources/writing/Modifiers Practice Questions.pdf",
    "downloadUrl": "resources/writing/Modifiers Practice Questions.pdf"
  },
  {
    "id": "writing-82",
    "title": "Punctuation Boundaries Practice Set 2",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Boundaries",
    "description": "Targeted Practice Questions — Boundaries. External SAT-style practice; set H2 (Homework 16)",
    "notes": "External SAT-style practice; set H2 (Homework 16)",
    "filePath": "resources/writing/Punctuation Boundaries Practice Set 2.pdf",
    "downloadUrl": "resources/writing/Punctuation Boundaries Practice Set 2.pdf"
  },
  {
    "id": "writing-76",
    "title": "Punctuation Boundaries Practice Set 3",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Boundaries",
    "description": "Targeted Practice Questions — Boundaries. External SAT-style practice; set H3",
    "notes": "External SAT-style practice; set H3",
    "filePath": "resources/writing/Punctuation Boundaries Practice Set 3.pdf",
    "downloadUrl": "resources/writing/Punctuation Boundaries Practice Set 3.pdf"
  },
  {
    "id": "writing-75",
    "title": "Punctuation Boundaries Practice Set 4",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Boundaries",
    "description": "Targeted Practice Questions — Boundaries. External SAT-style practice; set H4",
    "notes": "External SAT-style practice; set H4",
    "filePath": "resources/writing/Punctuation Boundaries Practice Set 4.pdf",
    "downloadUrl": "resources/writing/Punctuation Boundaries Practice Set 4.pdf"
  },
  {
    "id": "writing-74",
    "title": "Subject-Verb Agreement Plurality Practice",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "SVA - plurality",
    "description": "Targeted Practice Questions — SVA - plurality. External SAT-style practice",
    "notes": "External SAT-style practice",
    "filePath": "resources/writing/Subject-Verb Agreement Plurality Practice.pdf",
    "downloadUrl": "resources/writing/Subject-Verb Agreement Plurality Practice.pdf"
  },
  {
    "id": "writing-73",
    "title": "Subject-Verb Agreement Subject Practice",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "SVA - identifying subjects",
    "description": "Targeted Practice Questions — SVA - identifying subjects. External SAT-style practice",
    "notes": "External SAT-style practice",
    "filePath": "resources/writing/Subject-Verb Agreement Subject Practice.pdf",
    "downloadUrl": "resources/writing/Subject-Verb Agreement Subject Practice.pdf"
  },
  {
    "id": "writing-2",
    "title": "Writing Expression of Ideas Practice Questions",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Expression of Ideas",
    "description": "Targeted Practice Questions — Expression of Ideas. Externally released SAT-style practice (Aug 2025)",
    "notes": "Externally released SAT-style practice (Aug 2025)",
    "filePath": "resources/writing/Writing Expression of Ideas Practice Questions.pdf",
    "downloadUrl": "resources/writing/Writing Expression of Ideas Practice Questions.pdf"
  },
  {
    "id": "writing-64",
    "title": "Writing Practice Set 1",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Transitions and writing",
    "description": "Targeted Practice Questions — Transitions and writing. From book practice sets; scanned",
    "notes": "From book practice sets; scanned",
    "filePath": "resources/writing/Writing Practice Set 1.pdf",
    "downloadUrl": "resources/writing/Writing Practice Set 1.pdf"
  },
  {
    "id": "writing-65",
    "title": "Writing Practice Set 2",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Transitions and writing",
    "description": "Targeted Practice Questions — Transitions and writing. From book practice sets; scanned",
    "notes": "From book practice sets; scanned",
    "filePath": "resources/writing/Writing Practice Set 2.pdf",
    "downloadUrl": "resources/writing/Writing Practice Set 2.pdf"
  },
  {
    "id": "writing-66",
    "title": "Writing Practice Set 3",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Transitions and writing",
    "description": "Targeted Practice Questions — Transitions and writing. From book practice sets; scanned",
    "notes": "From book practice sets; scanned",
    "filePath": "resources/writing/Writing Practice Set 3.pdf",
    "downloadUrl": "resources/writing/Writing Practice Set 3.pdf"
  },
  {
    "id": "writing-67",
    "title": "Writing Practice Set 4",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Transitions and writing",
    "description": "Targeted Practice Questions — Transitions and writing. From book practice sets; scanned",
    "notes": "From book practice sets; scanned",
    "filePath": "resources/writing/Writing Practice Set 4.pdf",
    "downloadUrl": "resources/writing/Writing Practice Set 4.pdf"
  },
  {
    "id": "writing-68",
    "title": "Writing Practice Set 5",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Transitions and writing",
    "description": "Targeted Practice Questions — Transitions and writing. From book practice sets; scanned",
    "notes": "From book practice sets; scanned",
    "filePath": "resources/writing/Writing Practice Set 5.pdf",
    "downloadUrl": "resources/writing/Writing Practice Set 5.pdf"
  },
  {
    "id": "writing-6",
    "title": "Writing Standard English Conventions Practice Questions",
    "section": "Writing",
    "materialType": "Targeted Practice Questions",
    "topic": "Standard English Conventions",
    "description": "Targeted Practice Questions — Standard English Conventions. Externally released SAT-style practice (Aug 2025)",
    "notes": "Externally released SAT-style practice (Aug 2025)",
    "filePath": "resources/writing/Writing Standard English Conventions Practice Questions.pdf",
    "downloadUrl": "resources/writing/Writing Standard English Conventions Practice Questions.pdf"
  },
  {
    "id": "reading-writing-83",
    "title": "Reading Writing Practice Test 10 Module 1",
    "section": "Reading & Writing",
    "materialType": "Mini Practice Test",
    "topic": "Mixed RW, Module 1",
    "description": "Mini Practice Test — Mixed RW, Module 1. Homework 15; form d10",
    "notes": "Homework 15; form d10",
    "filePath": "resources/reading-writing/Reading Writing Practice Test 10 Module 1.pdf",
    "downloadUrl": "resources/reading-writing/Reading Writing Practice Test 10 Module 1.pdf"
  },
  {
    "id": "reading-writing-84",
    "title": "Reading Writing Practice Test 10 Module 2",
    "section": "Reading & Writing",
    "materialType": "Mini Practice Test",
    "topic": "Mixed RW, Module 2",
    "description": "Mini Practice Test — Mixed RW, Module 2. Homework 15; form d10",
    "notes": "Homework 15; form d10",
    "filePath": "resources/reading-writing/Reading Writing Practice Test 10 Module 2.pdf",
    "downloadUrl": "resources/reading-writing/Reading Writing Practice Test 10 Module 2.pdf"
  },
  {
    "id": "reading-writing-70",
    "title": "Reading Writing Practice Test 6 Module 1",
    "section": "Reading & Writing",
    "materialType": "Mini Practice Test",
    "topic": "Mixed RW, Module 1",
    "description": "Mini Practice Test — Mixed RW, Module 1. Used as course final; form d6",
    "notes": "Used as course final; form d6",
    "filePath": "resources/reading-writing/Reading Writing Practice Test 6 Module 1.pdf",
    "downloadUrl": "resources/reading-writing/Reading Writing Practice Test 6 Module 1.pdf"
  },
  {
    "id": "reading-writing-71",
    "title": "Reading Writing Practice Test 6 Module 2",
    "section": "Reading & Writing",
    "materialType": "Mini Practice Test",
    "topic": "Mixed RW, Module 2",
    "description": "Mini Practice Test — Mixed RW, Module 2. Used as course final; form d6",
    "notes": "Used as course final; form d6",
    "filePath": "resources/reading-writing/Reading Writing Practice Test 6 Module 2.pdf",
    "downloadUrl": "resources/reading-writing/Reading Writing Practice Test 6 Module 2.pdf"
  },
  {
    "id": "reading-writing-19",
    "title": "Reading Writing Practice Test 7 Module 1",
    "section": "Reading & Writing",
    "materialType": "Mini Practice Test",
    "topic": "Mixed RW, Module 1",
    "description": "Mini Practice Test — Mixed RW, Module 1. Used as diagnostic test (40 min); form d7",
    "notes": "Used as diagnostic test (40 min); form d7",
    "filePath": "resources/reading-writing/Reading Writing Practice Test 7 Module 1.pdf",
    "downloadUrl": "resources/reading-writing/Reading Writing Practice Test 7 Module 1.pdf"
  },
  {
    "id": "reading-writing-18",
    "title": "Reading Writing Practice Test 7 Module 2",
    "section": "Reading & Writing",
    "materialType": "Mini Practice Test",
    "topic": "Mixed RW, Module 2",
    "description": "Mini Practice Test — Mixed RW, Module 2. Used as diagnostic test (40 min); form d7",
    "notes": "Used as diagnostic test (40 min); form d7",
    "filePath": "resources/reading-writing/Reading Writing Practice Test 7 Module 2.pdf",
    "downloadUrl": "resources/reading-writing/Reading Writing Practice Test 7 Module 2.pdf"
  },
  {
    "id": "reading-writing-88",
    "title": "Reading Writing Practice Test 8 Module 1",
    "section": "Reading & Writing",
    "materialType": "Mini Practice Test",
    "topic": "Mixed RW, Module 1",
    "description": "Mini Practice Test — Mixed RW, Module 1. Homework 12; form d8",
    "notes": "Homework 12; form d8",
    "filePath": "resources/reading-writing/Reading Writing Practice Test 8 Module 1.pdf",
    "downloadUrl": "resources/reading-writing/Reading Writing Practice Test 8 Module 1.pdf"
  },
  {
    "id": "reading-writing-89",
    "title": "Reading Writing Practice Test 8 Module 2",
    "section": "Reading & Writing",
    "materialType": "Mini Practice Test",
    "topic": "Mixed RW, Module 2",
    "description": "Mini Practice Test — Mixed RW, Module 2. Homework 12; form d8",
    "notes": "Homework 12; form d8",
    "filePath": "resources/reading-writing/Reading Writing Practice Test 8 Module 2.pdf",
    "downloadUrl": "resources/reading-writing/Reading Writing Practice Test 8 Module 2.pdf"
  },
  {
    "id": "reading-writing-86",
    "title": "Reading Writing Practice Test 9 Module 1",
    "section": "Reading & Writing",
    "materialType": "Mini Practice Test",
    "topic": "Mixed RW, Module 1",
    "description": "Mini Practice Test — Mixed RW, Module 1. Homework 13; form d9",
    "notes": "Homework 13; form d9",
    "filePath": "resources/reading-writing/Reading Writing Practice Test 9 Module 1.pdf",
    "downloadUrl": "resources/reading-writing/Reading Writing Practice Test 9 Module 1.pdf"
  },
  {
    "id": "reading-writing-87",
    "title": "Reading Writing Practice Test 9 Module 2",
    "section": "Reading & Writing",
    "materialType": "Mini Practice Test",
    "topic": "Mixed RW, Module 2",
    "description": "Mini Practice Test — Mixed RW, Module 2. Homework 13; form d9",
    "notes": "Homework 13; form d9",
    "filePath": "resources/reading-writing/Reading Writing Practice Test 9 Module 2.pdf",
    "downloadUrl": "resources/reading-writing/Reading Writing Practice Test 9 Module 2.pdf"
  },
  {
    "id": "reading-writing-104",
    "title": "Reading and Writing Question Types Guide",
    "section": "Reading & Writing",
    "materialType": "Strategy Guide",
    "topic": "All RW question types",
    "description": "Strategy Guide — All RW question types. 40-page overview",
    "notes": "40-page overview",
    "filePath": "resources/reading-writing/Reading and Writing Question Types Guide.pdf",
    "downloadUrl": "resources/reading-writing/Reading and Writing Question Types Guide.pdf"
  }
];
